# Generated by Django 4.2.6 on 2023-10-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0002_disco_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Selo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produtora', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='disco',
            name='nome_produtora',
        ),
        migrations.AddField(
            model_name='disco',
            name='artistas',
            field=models.ManyToManyField(related_name='discos', to='atv.artista'),
        ),
        migrations.AddField(
            model_name='disco',
            name='selo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atv.selo'),
        ),
    ]
